version: 2

sources:
  - name: raw
    database: SEISAN_DB
    schema: RAW
    tables:
      - name: TMP_ANALOG
      - name: TMP_MIMAWARI
      - name: TMP_ZAIKO_HINMOKU
      - name: TMP_ZAIKO_MES
      - name: TMP_ZAIKO_TEIKIHACCHU
      - name: TMP_ZAIKO_JUKYU
