version: 2

sources:
  - name: raw
    database: REO_TEST
    schema: SHARE_POINT   # ← TESTがあるスキーマ
    tables:
      - name: TEST

  - name: manual
    database: REO_TEST
    schema: SHARE_POINT   # ← CLASS_BUSHOを作ったスキーマ（同じなら同じでOK）
    tables:
      - name: CLASS_BUSHO
