{{ config(
    materialized='table',
    alias='T_在庫_需給表'
) }}

with src as (
  select
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'NO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'SEQ_1', 'CAST(NULL AS NUMBER(18,0))') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'SEQ', 'CAST(NULL AS NUMBER(18,0))') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'SEIZOU_CENTER', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'SEIZOU_CENTER_CODE', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'HINBAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'HINMEI', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'DAIHYOU_SETSUBI', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'SEISAN_SETSUBI', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'JIGYOUSHO', 'CAST(NULL AS NUMBER(18,0))') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'JIGYOU_KUBUN', 'CAST(NULL AS NUMBER(18,0))') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'JIGYOU_MEISHOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'BAIKA', 'CAST(NULL AS NUMBER(18,0))') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'GENKA', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'KEIHI', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'HYOUJUN_SHURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'SEIHIN_2_CHUKANTAI_3', 'CAST(NULL AS NUMBER(18,0))') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'KOKEIKANSANRITSU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'ZENGETSU_SHIYOUSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'ZENGETSU_JUKYUNAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'ZENGETSU_JUKYUGAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'ZENGETSU_ZANTAIOU_KABUSOKU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'ZENGETSU_ZAIKORITSU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'ZENGETSU_SHIKAKARI', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_SHIRE', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_SEISAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_SEISANSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_HANBAISURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_SHIYOUSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_JUKYUNAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_JUKYUGAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_ZANTAIOU_KABUSOKU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_ZAIKORITSU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_SHIKAKARI', 'CAST(NULL AS VARCHAR)') }},

    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_1_SHIRE', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_1_SEISAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_1_SEISANSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_1_HANBAISURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_1_SHIYOUSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_1_JUKYUNAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_1_JUKYUGAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_1_ZANTAIOU_KABUSOKU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_1_ZAIKORITSU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_1_SHIKAKARI', 'CAST(NULL AS VARCHAR)') }},

    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_2_SHIRE', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_2_SEISAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_2_SEISANSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_2_HANBAISURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_2_SHIYOUSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_2_JUKYUNAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_2_JUKYUGAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_2_ZANTAIOU_KABUSOKU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_2_ZAIKORITSU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_2_SHIKAKARI', 'CAST(NULL AS VARCHAR)') }},

    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_3_SHIRE', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_3_SEISAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_3_SEISANSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_3_HANBAISURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_3_SHIYOUSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_3_JUKYUNAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_3_JUKYUGAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_3_ZANTAIOU_KABUSOKU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_3_ZAIKORITSU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_3_SHIKAKARI', 'CAST(NULL AS VARCHAR)') }},

    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_4_SHIRE', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_4_SEISAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_4_SEISANSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_4_HANBAISURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_4_SHIYOUSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_4_JUKYUNAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_4_JUKYUGAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_4_ZANTAIOU_KABUSOKU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_4_ZAIKORITSU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_4_SHIKAKARI', 'CAST(NULL AS VARCHAR)') }},

    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_5_SHIRE', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_5_SEISAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_5_SEISANSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_5_HANBAISURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_5_SHIYOUSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_5_JUKYUNAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_5_JUKYUGAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_5_ZANTAIOU_KABUSOKU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_5_ZAIKORITSU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_5_SHIKAKARI', 'CAST(NULL AS VARCHAR)') }},

    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_6_SHIRE', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_6_SEISAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_6_SEISANSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_6_HANBAISURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_6_SHIYOUSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_6_JUKYUNAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_6_JUKYUGAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_6_ZANTAIOU_KABUSOKU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_6_ZAIKORITSU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_6_SHIKAKARI', 'CAST(NULL AS VARCHAR)') }},

    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_7_SHIRE', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_7_SEISAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_7_SEISANSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_7_HANBAISURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_7_SHIYOUSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_7_JUKYUNAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_7_JUKYUGAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_7_ZANTAIOU_KABUSOKU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_7_ZAIKORITSU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_7_SHIKAKARI', 'CAST(NULL AS VARCHAR)') }},

    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_8_SHIRE', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_8_SEISAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_8_SEISANSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_8_HANBAISURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_8_SHIYOUSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_8_JUKYUNAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_8_JUKYUGAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_8_ZANTAIOU_KABUSOKU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_8_ZAIKORITSU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_8_SHIKAKARI', 'CAST(NULL AS VARCHAR)') }},

    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_9_SHIRE', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_9_SEISAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_9_SEISANSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_9_HANBAISURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_9_SHIYOUSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_9_JUKYUNAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_9_JUKYUGAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_9_ZANTAIOU_KABUSOKU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_9_ZAIKORITSU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_9_SHIKAKARI', 'CAST(NULL AS VARCHAR)') }},

    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_10_SHIRE', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_10_SEISAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_10_SEISANSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_10_HANBAISURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_10_SHIYOUSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_10_JUKYUNAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_10_JUKYUGAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_10_ZANTAIOU_KABUSOKU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_10_ZAIKORITSU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_10_SHIKAKARI', 'CAST(NULL AS VARCHAR)') }},

    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_11_SHIRE', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_11_SEISAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_11_SEISANSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_11_HANBAISURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_11_SHIYOUSURYOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_11_JUKYUNAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_11_JUKYUGAI_ZAIKO', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_11_ZANTAIOU_KABUSOKU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_11_ZAIKORITSU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'TOUGETSU_PLUS_11_SHIKAKARI', 'CAST(NULL AS VARCHAR)') }},

    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'HINBAN_2', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), 'HINMEI_2', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_JUKYU'), '_FILE', 'CAST(NULL AS VARCHAR)') }}
  from {{ source('raw','TMP_ZAIKO_JUKYU') }}
),

mapped as (
  select
    NO::varchar                                                  as "NO",
    TRY_TO_DECIMAL(TO_VARCHAR(SEQ_1), 18, 0)                      as "SEQ1",
    TRY_TO_DECIMAL(TO_VARCHAR(SEQ), 18, 0)                       as "SEQ",
    SEIZOU_CENTER::varchar                                       as "製造センター",
    SEIZOU_CENTER_CODE::varchar                                  as "製造センターコード",
    HINBAN::varchar                                              as "品番",
    HINMEI::varchar                                              as "品名",
    DAIHYOU_SETSUBI::varchar                                     as "代表設備",
    SEISAN_SETSUBI::varchar                                      as "生産設備",
    TRY_TO_DECIMAL(TO_VARCHAR(JIGYOUSHO), 18, 0)                 as "事業所",
    TRY_TO_DECIMAL(TO_VARCHAR(JIGYOU_KUBUN), 18, 0)              as "事業区分",
    JIGYOU_MEISHOU::varchar                                      as "事業名称",
    TRY_TO_DECIMAL(TO_VARCHAR(BAIKA), 18, 0)                     as "売価",
    GENKA::varchar                                               as "原価",
    TRY_TO_DECIMAL(TO_VARCHAR(KEIHI), 38, 3)                     as "経費",
    HYOUJUN_SHURYOU::varchar                                     as "標準収量",
    TRY_TO_DECIMAL(TO_VARCHAR(SEIHIN_2_CHUKANTAI_3), 18, 0)      as "製品=2／中間体=3",
    TRY_TO_DECIMAL(TO_VARCHAR(KOKEIKANSANRITSU), 38, 3)          as "固形換算率",

    ZENGETSU_SHIYOUSURYOU::varchar                               as "前月度実績使用数量",
    ZENGETSU_JUKYUNAI_ZAIKO::varchar                             as "前月度実績需給内在庫",
    ZENGETSU_JUKYUGAI_ZAIKO::varchar                             as "前月度実績需給外在庫",
    ZENGETSU_ZANTAIOU_KABUSOKU::varchar                          as "前月度実績前残対応過不足",
    ZENGETSU_ZAIKORITSU::varchar                                 as "前月度実績在庫率",
    ZENGETSU_SHIKAKARI::varchar                                  as "前月度実績仕掛#数",

    TOUGETSU_SHIRE::varchar                                      as "当月度見込仕込#数",
    TOUGETSU_SEISAN::varchar                                     as "当月度見込生産#数",
    TOUGETSU_SEISANSURYOU::varchar                               as "当月度見込生産数量",
    TOUGETSU_HANBAISURYOU::varchar                               as "当月度見込販売数量",
    TOUGETSU_SHIYOUSURYOU::varchar                               as "当月度見込使用数量",
    TOUGETSU_JUKYUNAI_ZAIKO::varchar                             as "当月度見込需給内在庫",
    TOUGETSU_JUKYUGAI_ZAIKO::varchar                             as "当月度見込需給外在庫",
    TOUGETSU_ZANTAIOU_KABUSOKU::varchar                          as "当月度見込前残対応過不足",
    TOUGETSU_ZAIKORITSU::varchar                                 as "当月度見込在庫率",
    TOUGETSU_SHIKAKARI::varchar                                  as "当月度見込仕掛#数",

    TOUGETSU_PLUS_1_SHIRE::varchar                               as "当月+1月度計画仕込#数",
    TOUGETSU_PLUS_1_SEISAN::varchar                              as "当月+1月度計画生産#数",
    TOUGETSU_PLUS_1_SEISANSURYOU::varchar                        as "当月+1月度計画生産数量",
    TOUGETSU_PLUS_1_HANBAISURYOU::varchar                        as "当月+1月度計画販売数量",
    TOUGETSU_PLUS_1_SHIYOUSURYOU::varchar                        as "当月+1月度計画使用数量",
    TOUGETSU_PLUS_1_JUKYUNAI_ZAIKO::varchar                      as "当月+1月度計画需給内在庫",
    TOUGETSU_PLUS_1_JUKYUGAI_ZAIKO::varchar                      as "当月+1月度計画需給外在庫",
    TOUGETSU_PLUS_1_ZANTAIOU_KABUSOKU::varchar                   as "当月+1月度計画前残対応過不足",
    TOUGETSU_PLUS_1_ZAIKORITSU::varchar                          as "当月+1月度計画在庫率",
    TOUGETSU_PLUS_1_SHIKAKARI::varchar                           as "当月+1月度計画仕掛#数",

    TOUGETSU_PLUS_2_SHIRE::varchar                               as "当月+2月度計画仕込#数",
    TOUGETSU_PLUS_2_SEISAN::varchar                              as "当月+2月度計画生産#数",
    TOUGETSU_PLUS_2_SEISANSURYOU::varchar                        as "当月+2月度計画生産数量",
    TOUGETSU_PLUS_2_HANBAISURYOU::varchar                        as "当月+2月度計画販売数量",
    TOUGETSU_PLUS_2_SHIYOUSURYOU::varchar                        as "当月+2月度計画使用数量",
    TOUGETSU_PLUS_2_JUKYUNAI_ZAIKO::varchar                      as "当月+2月度計画需給内在庫",
    TOUGETSU_PLUS_2_JUKYUGAI_ZAIKO::varchar                      as "当月+2月度計画需給外在庫",
    TOUGETSU_PLUS_2_ZANTAIOU_KABUSOKU::varchar                   as "当月+2月度計画前残対応過不足",
    TOUGETSU_PLUS_2_ZAIKORITSU::varchar                          as "当月+2月度計画在庫率",
    TOUGETSU_PLUS_2_SHIKAKARI::varchar                           as "当月+2月度計画仕掛#数",

    TOUGETSU_PLUS_3_SHIRE::varchar                               as "当月+3月度計画仕込#数",
    TOUGETSU_PLUS_3_SEISAN::varchar                              as "当月+3月度計画生産#数",
    TOUGETSU_PLUS_3_SEISANSURYOU::varchar                        as "当月+3月度計画生産数量",
    TOUGETSU_PLUS_3_HANBAISURYOU::varchar                        as "当月+3月度計画販売数量",
    TOUGETSU_PLUS_3_SHIYOUSURYOU::varchar                        as "当月+3月度計画使用数量",
    TOUGETSU_PLUS_3_JUKYUNAI_ZAIKO::varchar                      as "当月+3月度計画需給内在庫",
    TOUGETSU_PLUS_3_JUKYUGAI_ZAIKO::varchar                      as "当月+3月度計画需給外在庫",
    TOUGETSU_PLUS_3_ZANTAIOU_KABUSOKU::varchar                   as "当月+3月度計画前残対応過不足",
    TOUGETSU_PLUS_3_ZAIKORITSU::varchar                          as "当月+3月度計画在庫率",
    TOUGETSU_PLUS_3_SHIKAKARI::varchar                           as "当月+3月度計画仕掛#数",

    TOUGETSU_PLUS_4_SHIRE::varchar                               as "当月+4月度計画仕込#数",
    TOUGETSU_PLUS_4_SEISAN::varchar                              as "当月+4月度計画生産#数",
    TOUGETSU_PLUS_4_SEISANSURYOU::varchar                        as "当月+4月度計画生産数量",
    TOUGETSU_PLUS_4_HANBAISURYOU::varchar                        as "当月+4月度計画販売数量",
    TOUGETSU_PLUS_4_SHIYOUSURYOU::varchar                        as "当月+4月度計画使用数量",
    TOUGETSU_PLUS_4_JUKYUNAI_ZAIKO::varchar                      as "当月+4月度計画需給内在庫",
    TOUGETSU_PLUS_4_JUKYUGAI_ZAIKO::varchar                      as "当月+4月度計画需給外在庫",
    TOUGETSU_PLUS_4_ZANTAIOU_KABUSOKU::varchar                   as "当月+4月度計画前残対応過不足",
    TOUGETSU_PLUS_4_ZAIKORITSU::varchar                          as "当月+4月度計画在庫率",
    TOUGETSU_PLUS_4_SHIKAKARI::varchar                           as "当月+4月度計画仕掛#数",

    TOUGETSU_PLUS_5_SHIRE::varchar                               as "当月+5月度計画仕込#数",
    TOUGETSU_PLUS_5_SEISAN::varchar                              as "当月+5月度計画生産#数",
    TOUGETSU_PLUS_5_SEISANSURYOU::varchar                        as "当月+5月度計画生産数量",
    TOUGETSU_PLUS_5_HANBAISURYOU::varchar                        as "当月+5月度計画販売数量",
    TOUGETSU_PLUS_5_SHIYOUSURYOU::varchar                        as "当月+5月度計画使用数量",
    TOUGETSU_PLUS_5_JUKYUNAI_ZAIKO::varchar                      as "当月+5月度計画需給内在庫",
    TOUGETSU_PLUS_5_JUKYUGAI_ZAIKO::varchar                      as "当月+5月度計画需給外在庫",
    TOUGETSU_PLUS_5_ZANTAIOU_KABUSOKU::varchar                   as "当月+5月度計画前残対応過不足",
    TOUGETSU_PLUS_5_ZAIKORITSU::varchar                          as "当月+5月度計画在庫率",
    TOUGETSU_PLUS_5_SHIKAKARI::varchar                           as "当月+5月度計画仕掛#数",

    TOUGETSU_PLUS_6_SHIRE::varchar                               as "当月+6月度計画仕込#数",
    TOUGETSU_PLUS_6_SEISAN::varchar                              as "当月+6月度計画生産#数",
    TOUGETSU_PLUS_6_SEISANSURYOU::varchar                        as "当月+6月度計画生産数量",
    TOUGETSU_PLUS_6_HANBAISURYOU::varchar                        as "当月+6月度計画販売数量",
    TOUGETSU_PLUS_6_SHIYOUSURYOU::varchar                        as "当月+6月度計画使用数量",
    TOUGETSU_PLUS_6_JUKYUNAI_ZAIKO::varchar                      as "当月+6月度計画需給内在庫",
    TOUGETSU_PLUS_6_JUKYUGAI_ZAIKO::varchar                      as "当月+6月度計画需給外在庫",
    TOUGETSU_PLUS_6_ZANTAIOU_KABUSOKU::varchar                   as "当月+6月度計画前残対応過不足",
    TOUGETSU_PLUS_6_ZAIKORITSU::varchar                          as "当月+6月度計画在庫率",
    TOUGETSU_PLUS_6_SHIKAKARI::varchar                           as "当月+6月度計画仕掛#数",

    TOUGETSU_PLUS_7_SHIRE::varchar                               as "当月+7月度計画仕込#数",
    TOUGETSU_PLUS_7_SEISAN::varchar                              as "当月+7月度計画生産#数",
    TOUGETSU_PLUS_7_SEISANSURYOU::varchar                        as "当月+7月度計画生産数量",
    TOUGETSU_PLUS_7_HANBAISURYOU::varchar                        as "当月+7月度計画販売数量",
    TOUGETSU_PLUS_7_SHIYOUSURYOU::varchar                        as "当月+7月度計画使用数量",
    TOUGETSU_PLUS_7_JUKYUNAI_ZAIKO::varchar                      as "当月+7月度計画需給内在庫",
    TOUGETSU_PLUS_7_JUKYUGAI_ZAIKO::varchar                      as "当月+7月度計画需給外在庫",
    TOUGETSU_PLUS_7_ZANTAIOU_KABUSOKU::varchar                   as "当月+7月度計画前残対応過不足",
    TOUGETSU_PLUS_7_ZAIKORITSU::varchar                          as "当月+7月度計画在庫率",
    TOUGETSU_PLUS_7_SHIKAKARI::varchar                           as "当月+7月度計画仕掛#数",

    TOUGETSU_PLUS_8_SHIRE::varchar                               as "当月+8月度計画仕込#数",
    TOUGETSU_PLUS_8_SEISAN::varchar                              as "当月+8月度計画生産#数",
    TOUGETSU_PLUS_8_SEISANSURYOU::varchar                        as "当月+8月度計画生産数量",
    TOUGETSU_PLUS_8_HANBAISURYOU::varchar                        as "当月+8月度計画販売数量",
    TOUGETSU_PLUS_8_SHIYOUSURYOU::varchar                        as "当月+8月度計画使用数量",
    TOUGETSU_PLUS_8_JUKYUNAI_ZAIKO::varchar                      as "当月+8月度計画需給内在庫",
    TOUGETSU_PLUS_8_JUKYUGAI_ZAIKO::varchar                      as "当月+8月度計画需給外在庫",
    TOUGETSU_PLUS_8_ZANTAIOU_KABUSOKU::varchar                   as "当月+8月度計画前残対応過不足",
    TOUGETSU_PLUS_8_ZAIKORITSU::varchar                          as "当月+8月度計画在庫率",
    TOUGETSU_PLUS_8_SHIKAKARI::varchar                           as "当月+8月度計画仕掛#数",

    TOUGETSU_PLUS_9_SHIRE::varchar                               as "当月+9月度計画仕込#数",
    TOUGETSU_PLUS_9_SEISAN::varchar                              as "当月+9月度計画生産#数",
    TOUGETSU_PLUS_9_SEISANSURYOU::varchar                        as "当月+9月度計画生産数量",
    TOUGETSU_PLUS_9_HANBAISURYOU::varchar                        as "当月+9月度計画販売数量",
    TOUGETSU_PLUS_9_SHIYOUSURYOU::varchar                        as "当月+9月度計画使用数量",
    TOUGETSU_PLUS_9_JUKYUNAI_ZAIKO::varchar                      as "当月+9月度計画需給内在庫",
    TOUGETSU_PLUS_9_JUKYUGAI_ZAIKO::varchar                      as "当月+9月度計画需給外在庫",
    TOUGETSU_PLUS_9_ZANTAIOU_KABUSOKU::varchar                   as "当月+9月度計画前残対応過不足",
    TOUGETSU_PLUS_9_ZAIKORITSU::varchar                          as "当月+9月度計画在庫率",
    TOUGETSU_PLUS_9_SHIKAKARI::varchar                           as "当月+9月度計画仕掛#数",

    TOUGETSU_PLUS_10_SHIRE::varchar                              as "当月+10月度計画仕込#数",
    TOUGETSU_PLUS_10_SEISAN::varchar                             as "当月+10月度計画生産#数",
    TOUGETSU_PLUS_10_SEISANSURYOU::varchar                       as "当月+10月度計画生産数量",
    TOUGETSU_PLUS_10_HANBAISURYOU::varchar                       as "当月+10月度計画販売数量",
    TOUGETSU_PLUS_10_SHIYOUSURYOU::varchar                       as "当月+10月度計画使用数量",
    TOUGETSU_PLUS_10_JUKYUNAI_ZAIKO::varchar                     as "当月+10月度計画需給内在庫",
    TOUGETSU_PLUS_10_JUKYUGAI_ZAIKO::varchar                     as "当月+10月度計画需給外在庫",
    TOUGETSU_PLUS_10_ZANTAIOU_KABUSOKU::varchar                  as "当月+10月度計画前残対応過不足",
    TOUGETSU_PLUS_10_ZAIKORITSU::varchar                         as "当月+10月度計画在庫率",
    TOUGETSU_PLUS_10_SHIKAKARI::varchar                          as "当月+10月度計画仕掛#数",

    TOUGETSU_PLUS_11_SHIRE::varchar                              as "当月+11月度計画仕込#数",
    TOUGETSU_PLUS_11_SEISAN::varchar                             as "当月+11月度計画生産#数",
    TOUGETSU_PLUS_11_SEISANSURYOU::varchar                       as "当月+11月度計画生産数量",
    TOUGETSU_PLUS_11_HANBAISURYOU::varchar                       as "当月+11月度計画販売数量",
    TOUGETSU_PLUS_11_SHIYOUSURYOU::varchar                       as "当月+11月度計画使用数量",
    TOUGETSU_PLUS_11_JUKYUNAI_ZAIKO::varchar                     as "当月+11月度計画需給内在庫",
    TOUGETSU_PLUS_11_JUKYUGAI_ZAIKO::varchar                     as "当月+11月度計画需給外在庫",
    TOUGETSU_PLUS_11_ZANTAIOU_KABUSOKU::varchar                  as "当月+11月度計画前残対応過不足",
    TOUGETSU_PLUS_11_ZAIKORITSU::varchar                         as "当月+11月度計画在庫率",
    TOUGETSU_PLUS_11_SHIKAKARI::varchar                          as "当月+11月度計画仕掛#数",

    HINBAN_2::varchar                                             as "品番2",
    HINMEI_2::varchar                                             as "品名2",

    -- 日付：ファイル名内の連続8桁を抽出
    TO_DATE(REGEXP_SUBSTR(_FILE, '[0-9]{8}'), 'YYYYMMDD')        as "日付"
  from src
)

select *
from mapped
