{{ config(
    materialized='table',
    alias='T_在庫_定期発注ベース'
) }}

with src as (
  select
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'F001', 'CAST(NULL AS NUMBER(18,0))') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'F002', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'JIGYOUJOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'GENRYOU_CODE', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'SHANAIYOU_MEISHOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'GENKATANKA', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'BOMBE_STORAGE', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'YUNYU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOKUCHU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'GENRYOU_KUBUN', 'CAST(NULL AS NUMBER(18,0))') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'KOUNYU_LT', 'CAST(NULL AS NUMBER(18,0))') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'IDOU_LT', 'CAST(NULL AS NUMBER(18,0))') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'HACCHU_LT', 'CAST(NULL AS NUMBER(18,0))') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'HACCHU_TANI', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'SAISHO_HACCHURYOU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'ZENZAN_SOUKOZAIKO_NG_HORYU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'ZENZAN_SOUKOZAIKO_HOSHOUGIRE', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'ZENZAN_SOUKOZAIKO_GOUKAKU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'ZENZAN_GENBAZAIKO', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'ZENZAN_RYOUHIN_ZANZAIKO', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_MIKOMI_KOUNYU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_MIKOMI_NOUKI', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_MIKOMI_SHIYOU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_MIKOMI_SUIZAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_1_KOUNYU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_1_NOUKI', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_1_SHIYOU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_1_SUIZAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_2_KOUNYU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_2_NOUKI', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_2_SHIYOU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_2_SUIZAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_3_KOUNYU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_3_NOUKI', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_3_SHIYOU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_3_SUIZAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_4_KOUNYU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_4_NOUKI', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_4_SHIYOU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_4_SUIZAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_5_KOUNYU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_5_NOUKI', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_5_SHIYOU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_5_SUIZAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_6_KOUNYU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_6_NOUKI', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_6_SHIYOU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_6_SUIZAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_7_KOUNYU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_7_NOUKI', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_7_SHIYOU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_7_SUIZAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_8_KOUNYU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_8_NOUKI', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_8_SHIYOU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_8_SUIZAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_9_KOUNYU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_9_NOUKI', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_9_SHIYOU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_9_SUIZAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_10_KOUNYU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_10_NOUKI', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_10_SHIYOU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_10_SUIZAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_11_KOUNYU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_11_NOUKI', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_11_SHIYOU', 'CAST(NULL AS FLOAT)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'TOUGETSU_PLUS_11_SUIZAN', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), 'BIKOU', 'CAST(NULL AS VARCHAR)') }},
    {{ optional_col(source('raw','TMP_ZAIKO_TEIKIHACCHU'), '_FILE', 'CAST(NULL AS VARCHAR)') }}
  from {{ source('raw','TMP_ZAIKO_TEIKIHACCHU') }}
),

mapped as (
  select
    TRY_TO_DECIMAL(TO_VARCHAR(F001), 18, 0)                       as "F001",
    F002::varchar                                                 as "F002",
    JIGYOUJOU::varchar                                            as "事業場",
    GENRYOU_CODE::varchar                                         as "原料コード",
    SHANAIYOU_MEISHOU::varchar                                    as "社内用名称",
    GENKATANKA::float                                             as "原価単価",
    BOMBE_STORAGE::varchar                                        as "ボンベ　ストレージ",
    YUNYU::varchar                                                as "輸入",
    TOKUCHU::varchar                                              as "特注",
    TRY_TO_DECIMAL(TO_VARCHAR(GENRYOU_KUBUN), 18, 0)              as "原料区分",
    TRY_TO_DECIMAL(TO_VARCHAR(KOUNYU_LT), 18, 0)                  as "購入　L／T",
    TRY_TO_DECIMAL(TO_VARCHAR(IDOU_LT), 18, 0)                    as "移動　L／T",
    TRY_TO_DECIMAL(TO_VARCHAR(HACCHU_LT), 18, 0)                  as "発注　L／T",
    TRY_TO_DECIMAL(TO_VARCHAR(HACCHU_TANI), 38, 3)                as "発注単位",
    TRY_TO_DECIMAL(TO_VARCHAR(SAISHO_HACCHURYOU), 38, 3)          as "最小発注量",
    TRY_TO_DECIMAL(TO_VARCHAR(ZENZAN_SOUKOZAIKO_NG_HORYU), 38, 3) as "前残　倉庫在庫　NG・保留",
    TRY_TO_DECIMAL(TO_VARCHAR(ZENZAN_SOUKOZAIKO_HOSHOUGIRE), 38, 3) as "前残　倉庫在庫　保証切れ",
    TRY_TO_DECIMAL(TO_VARCHAR(ZENZAN_SOUKOZAIKO_GOUKAKU), 38, 3)  as "前残　倉庫在庫　合格",
    TRY_TO_DECIMAL(TO_VARCHAR(ZENZAN_GENBAZAIKO), 38, 3)          as "前残　現場在庫",
    TRY_TO_DECIMAL(TO_VARCHAR(ZENZAN_RYOUHIN_ZANZAIKO), 38, 3)    as "前残　良品残在庫",

    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_MIKOMI_KOUNYU), 38, 3)     as "当月見込　購入",
    TOUGETSU_MIKOMI_NOUKI::varchar                                as "当月見込　納期",
    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_MIKOMI_SHIYOU), 38, 3)     as "当月見込　使用",
    TOUGETSU_MIKOMI_SUIZAN::varchar                               as "当月見込　推残",

    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_1_KOUNYU), 38, 3)     as "当月+1　購入",
    TOUGETSU_PLUS_1_NOUKI::varchar                                as "当月+1　納期",
    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_1_SHIYOU), 38, 3)     as "当月+1　使用",
    TOUGETSU_PLUS_1_SUIZAN::varchar                               as "当月+1　推残",

    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_2_KOUNYU), 38, 3)     as "当月+2　購入",
    TOUGETSU_PLUS_2_NOUKI::varchar                                as "当月+2　納期",
    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_2_SHIYOU), 38, 3)     as "当月+2　使用",
    TOUGETSU_PLUS_2_SUIZAN::varchar                               as "当月+2　推残",

    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_3_KOUNYU), 38, 3)     as "当月+3　購入",
    TOUGETSU_PLUS_3_NOUKI::varchar                                as "当月+3　納期",
    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_3_SHIYOU), 38, 3)     as "当月+3　使用",
    TOUGETSU_PLUS_3_SUIZAN::varchar                               as "当月+3　推残",

    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_4_KOUNYU), 38, 3)     as "当月+4　購入",
    TOUGETSU_PLUS_4_NOUKI::varchar                                as "当月+4　納期",
    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_4_SHIYOU), 38, 3)     as "当月+4　使用",
    TOUGETSU_PLUS_4_SUIZAN::varchar                               as "当月+4　推残",

    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_5_KOUNYU), 38, 3)     as "当月+5　購入",
    TOUGETSU_PLUS_5_NOUKI::varchar                                as "当月+5　納期",
    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_5_SHIYOU), 38, 3)     as "当月+5　使用",
    TOUGETSU_PLUS_5_SUIZAN::varchar                               as "当月+5　推残",

    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_6_KOUNYU), 38, 3)     as "当月+6　購入",
    TOUGETSU_PLUS_6_NOUKI::varchar                                as "当月+6　納期",
    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_6_SHIYOU), 38, 3)     as "当月+6　使用",
    TOUGETSU_PLUS_6_SUIZAN::varchar                               as "当月+6　推残",

    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_7_KOUNYU), 38, 3)     as "当月+7　購入",
    TOUGETSU_PLUS_7_NOUKI::varchar                                as "当月+7　納期",
    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_7_SHIYOU), 38, 3)     as "当月+7　使用",
    TOUGETSU_PLUS_7_SUIZAN::varchar                               as "当月+7　推残",

    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_8_KOUNYU), 38, 3)     as "当月+8　購入",
    TOUGETSU_PLUS_8_NOUKI::varchar                                as "当月+8　納期",
    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_8_SHIYOU), 38, 3)     as "当月+8　使用",
    TOUGETSU_PLUS_8_SUIZAN::varchar                               as "当月+8　推残",

    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_9_KOUNYU), 38, 3)     as "当月+9　購入",
    TOUGETSU_PLUS_9_NOUKI::varchar                                as "当月+9　納期",
    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_9_SHIYOU), 38, 3)     as "当月+9　使用",
    TOUGETSU_PLUS_9_SUIZAN::varchar                               as "当月+9　推残",

    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_10_KOUNYU), 38, 3)    as "当月+10　購入",
    TOUGETSU_PLUS_10_NOUKI::varchar                               as "当月+10　納期",
    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_10_SHIYOU), 38, 3)    as "当月+10　使用",
    TOUGETSU_PLUS_10_SUIZAN::varchar                              as "当月+10　推残",

    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_11_KOUNYU), 38, 3)    as "当月+11　購入",
    TOUGETSU_PLUS_11_NOUKI::varchar                               as "当月+11　納期",
    TRY_TO_DECIMAL(TO_VARCHAR(TOUGETSU_PLUS_11_SHIYOU), 38, 3)    as "当月+11　使用",
    TOUGETSU_PLUS_11_SUIZAN::varchar                              as "当月+11　推残",

    BIKOU::varchar                                                as "備考",

    -- 日付：ファイル名末尾のYYYYMMDDを抽出
    TO_DATE(REGEXP_SUBSTR(_FILE, '[0-9]{8}$'), 'YYYYMMDD')        as "日付"
  from src
)

select *
from mapped
